import base64
import io
from datetime import datetime

from fpdf import FPDF
from PIL import Image


class NeuroLensReport(FPDF):
    def header(self):
        # Arial bold 15
        self.set_font("helvetica", "B", 20)
        # Move to the right
        self.set_text_color(30, 58, 138)  # Deep Blue
        self.cell(0, 10, "NeuroLens AI", ln=True, align="L")
        self.set_font("helvetica", "", 10)
        self.set_text_color(100)
        self.cell(0, 10, "Advanced Alzheimer's MRI Analysis Report", ln=True, align="L")
        # Line break
        self.ln(5)
        self.set_draw_color(200)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(10)

    def footer(self):
        # Position at 1.5 cm from bottom
        self.set_y(-15)
        # Arial italic 8
        self.set_font("helvetica", "I", 8)
        self.set_text_color(128)
        # Page number
        self.cell(0, 10, f"Page {self.page_no()} | Generated by NeuroLens AI System | {datetime.now().strftime('%Y-%m-%d %H:%M')}", 0, 0, "C")


def _draw_labeled_image(pdf, image_bytes, x, y, w, label):
    image = Image.open(io.BytesIO(image_bytes))
    pdf.image(image, x=x, y=y, w=w)
    pdf.set_xy(x, y + 87)
    pdf.set_font("helvetica", "B", 10)
    pdf.cell(w, 8, label, align="C")


def generate_report_pdf(analysis, gradcam_base64=None, lime_base64=None):
    pdf = NeuroLensReport()
    pdf.add_page()
    pdf.set_font("helvetica", size=12)

    # Patient / Scan Information
    pdf.set_font("helvetica", "B", 14)
    pdf.set_fill_color(241, 245, 249)
    pdf.cell(0, 10, "  Analysis Information", ln=True, fill=True)
    pdf.ln(2)

    pdf.set_font("helvetica", "", 10)
    col_width = 45
    pdf.set_text_color(100)
    pdf.cell(col_width, 8, "Analysis ID:")
    pdf.set_text_color(0)
    pdf.cell(0, 8, f"#{analysis['id']}", ln=True)

    pdf.set_text_color(100)
    pdf.cell(col_width, 8, "Scan Date:")
    pdf.set_text_color(0)
    pdf.cell(0, 8, analysis["created_at"], ln=True)

    pdf.set_text_color(100)
    pdf.cell(col_width, 8, "Original Filename:")
    pdf.set_text_color(0)
    pdf.cell(0, 8, analysis["filename"], ln=True)

    pdf.ln(10)

    # Prediction Results
    pdf.set_font("helvetica", "B", 14)
    pdf.set_fill_color(241, 245, 249)
    pdf.cell(0, 10, "  Clinical Prediction Results", ln=True, fill=True)
    pdf.ln(5)

    # Highlighted Result
    label = analysis["label"].upper()
    confidence = analysis["confidence"] * 100

    pdf.set_font("helvetica", "B", 12)
    pdf.cell(0, 10, "Primary Finding:", ln=False)
    pdf.set_font("helvetica", "B", 16)

    # Color code labels
    if "NO IMPAIRMENT" in label:
        pdf.set_text_color(34, 197, 94)  # Green
    elif "VERY MILD" in label:
        pdf.set_text_color(59, 130, 246)  # Blue
    elif "MILD" in label:
        pdf.set_text_color(245, 158, 11)  # Amber
    else:
        pdf.set_text_color(239, 68, 68)  # Red

    pdf.cell(0, 10, f"  {label}", ln=True)
    pdf.set_text_color(0)

    pdf.set_font("helvetica", "", 12)
    pdf.cell(0, 10, f"Confidence Score: {confidence:.2f}%", ln=True)
    pdf.ln(5)

    # Detailed Probabilities Chart (Simulated with text/rects)
    pdf.set_font("helvetica", "B", 10)
    pdf.cell(0, 10, "Class Probabilities Breakdown:", ln=True)
    pdf.set_font("helvetica", "", 9)

    for i, cls_name in enumerate(analysis["classes"]):
        prob = analysis["probabilities"][i] * 100
        pdf.cell(50, 6, cls_name)
        # Draw a small bar
        pdf.set_fill_color(220, 220, 220)
        pdf.rect(60, pdf.get_y() + 1, 100, 4, "F")
        pdf.set_fill_color(30, 58, 138)
        pdf.rect(60, pdf.get_y() + 1, max(1, prob), 4, "F")
        pdf.set_x(165)
        pdf.cell(20, 6, f"{prob:.1f}%", ln=True)

    pdf.ln(10)

    # Images Section
    pdf.set_font("helvetica", "B", 14)
    pdf.set_fill_color(241, 245, 249)
    pdf.cell(0, 10, "  Visual Analysis & Explainability", ln=True, fill=True)
    pdf.ln(5)

    y_before_images = pdf.get_y()
    image_width = 58
    image_x_positions = [12, 76, 140]
    rendered_any_explanation = False

    _draw_labeled_image(pdf, analysis["image_bytes"], image_x_positions[0], y_before_images + 5, image_width, "Original MRI Scan")

    if gradcam_base64:
        rendered_any_explanation = True
        _draw_labeled_image(
            pdf,
            base64.b64decode(gradcam_base64),
            image_x_positions[1],
            y_before_images + 5,
            image_width,
            "Grad-CAM Map",
        )

    if lime_base64:
        rendered_any_explanation = True
        _draw_labeled_image(
            pdf,
            base64.b64decode(lime_base64),
            image_x_positions[2],
            y_before_images + 5,
            image_width,
            "LIME Map",
        )

    if not rendered_any_explanation:
        pdf.set_xy(76, y_before_images + 36)
        pdf.set_font("helvetica", "I", 10)
        pdf.set_text_color(150)
        pdf.multi_cell(118, 5, "No explanation map was generated for this report session.", align="C")
        pdf.set_text_color(0)

    pdf.set_y(y_before_images + 100)

    # Disclaimer
    pdf.set_y(-40)
    pdf.set_font("helvetica", "B", 10)
    pdf.set_text_color(220, 38, 38)  # Red
    pdf.cell(0, 10, "DISCLAIMER", ln=True, align="C")
    pdf.set_font("helvetica", "", 8)
    pdf.set_text_color(100)
    disclaimer = (
        "This report is generated by an Artificial Intelligence system for research and educational purposes only. "
        "It does NOT constitute a clinical diagnosis. The findings should be reviewed by a qualified medical professional. "
        "AI models can have errors or biases; radiological interpretation requires clinical correlation."
    )
    pdf.multi_cell(0, 4, disclaimer, align="C")

    return pdf.output()
